### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by linuxproducer** [grantwinney/hide-comments-in-chrome-sites#1]
Here's a new site I'd like you to consider blocking:

https://www.facebook.com/groups/trogiup24h/?ref=nf_target&fref=nf

(please include any other relevant details)

**Comment by grantwinney** [comment]
Ugh, didn't see this because GitHub won't notify me of issues on my own repos unless I'm "watching" them, and I wasn't watching this one. Sorry for the late response @linuxproducer.

I do have blocks in place for Facebook, although I should check them closely, since they may have changed or added elements that affect how this plugin works. I'd hope this would work across all of Facebook, and that I wouldn't have to do anything special for individual groups. I'll check it out.

**Comment by grantwinney** [comment]
Well, I took a more heavy-handed approach that should work, but it hides the "like" and "share" links too. Facebook seems to randomly generate some of their class names and stuff, and it makes it difficult to rely on them to block certain elements. If you get a chance, try updating the definitions on the options page and try it again. Thanks.
