### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by jacobaarseth** [grantwinney/hide-comments-in-chrome-sites#2]
Here's a new site I'd like you to consider blocking:

https://www.youtube.com/watch

(please include any other relevant details)

**Comment by grantwinney** [comment]
Ugh, didn't see this because GitHub won't notify me of issues on my own repos unless I'm "watching" them, and I wasn't watching this one. Sorry for the late response @jacobaarseth.

I do block comments on YouTube, but it's possible they updated/added some new elements. Or maybe the patterns I'm using don't block the `/watch` URL. I'll check it out.

**Comment by grantwinney** [comment]
I checked YouTube. Comments on it are still blocked, as far as I can tell. If you're still seeing them, can you let me know where? A specific video or section of the site?
