### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by caioesteves** [grantwinney/hide-comments-in-chrome-sites#21]
Here's a new site I'd like you to consider blocking:

https://g1.globo.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Comments are already hidden on there as far I can tell, since they use a `comments` class around the comments section (something I block on all sites by default).

You still seem comments on there? Is there a specific story you're seeing them on? Do you see any errors or other seemingly related messages in the [dev tools console](https://grantwinney.com/how-do-i-view-the-dev-console-in-my-browser/)?

**Comment by grantwinney** [comment]
Let me know if you have more details and I'll reopen this.
