### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by jaygatto** [grantwinney/hide-comments-in-chrome-sites#33]
Here's a new site I'd like you to consider blocking:

https://www.dailykos.com

I suggest this not because of the often rather inane commenting, rarely sticking to the subject, but more from the point of view of the quantity of commenting making the page almost impossible to load the page at a reasonable rate.

**Comment by grantwinney** [comment]
Since they already enclose their comments area in a class named "comments", the extension should block them by default. And it does for me. Do you still get comments loading on, for example, this page?

https://www.dailykos.com/stories/2019/9/17/1886043/-Corey-Lewandoski-hearing-shows-that-any-impeachment-inquiry-is-going-to-require-much-tougher-rules#read-more

**Comment by grantwinney** [comment]
Added a separate line for dailykos. Let me know if you still see comments.
